spring.application.name=admin-dashboard

# To view the database tables
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Database connection settings
spring.datasource.url=jdbc:h2:mem:ticketflowdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# To create your database tables automatically on startup
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
